### ISSUE TITLE
CORS Blocked

### ISSUE THREAD

**Issue by jftuga** [BekBrace/VueJS-Flask-Full-Stack-Application#1]
In Firefox, if you see a message like:

    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5000/shark. 
    (Reason: CORS request did not succeed)

Then try changing hostname to **your server IP** address instead of `localhost` on this line:

https://github.com/BekBrace/VueJS-Flask-Full-Stack-Application/blob/master/frontend/frontend/src/components/Shark.vue#L19

Example:

    // from:
    const path = 'http://localhost:5000/shark';

    // to:
    const path = 'http://l192.168.0.8:5000/shark';

**Comment by BekBrace** [comment]
Thanks a lot for the tip, it was very helpful
